# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: 
  name: Kaushik_Laptop # Name of a pool. 
  vmImage: DESKTOP-A9DASJR

steps:    
- task: CmdLine@2
  displayName: Download ISTIO
  inputs:
    script: |
      helm repo add istio https://istio-release.storage.googleapis.com/charts
      helm repo update

- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'Azure subscription 1(1bd78ea7-13c0-4d71-bc70-b6a822ea4a46)'
    KeyVaultName: 'ghost-kv'
    SecretsFilter: '*'
    RunAsPreJob: false

- task: CmdLine@2
  displayName: az login
  inputs:
    script: |
      az login -u 93031176-d2d8-4035-b9ef-00b5a4febee6 -p $(sp-password)
      az account set --subscription 1bd78ea7-13c0-4d71-bc70-b6a822ea4a46
      az aks get-credentials --resource-group rg-nordcloud-ghost --name ghost-k8s-cluster

- task: CmdLine@2
  displayName: install istio system
  inputs:
    script: |
      kubectl create namespace istio-system
      helm install istio-base istio/base -n istio-system
      helm upgrade --install istiod istio/istiod -n istio-system #--wait

- task: CmdLine@2
  displayName: install istio ingress
  inputs:
    script: |
      kubectl create namespace istio-ingress
      kubectl label namespace istio-ingress istio-injection=enabled
      helm upgrade --install istio-ingress istio/gateway -n istio-ingress

- task: CmdLine@2
  displayName: install ghost
  inputs:
    script: |
      kubectl label namespace default istio-injection=enabled
      helm upgrade --install ghost-nordcloud ./ghost-nordcloud/