# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: 
  name: Kaushik_Laptop # Name of a pool. 
  vmImage: DESKTOP-A9DASJR

steps:    

- task: CmdLine@2
  displayName: az login
  inputs:
    script: |
      az login --service-principal -u 93031176-d2d8-4035-b9ef-00b5a4febee6 -p U.4p51.gLtiR10Yemwzd5weld9-Z6X5Blk --tenant bad3cd3d-a88a-478d-a251-43f7355aad77
      az account set --subscription 1bd78ea7-13c0-4d71-bc70-b6a822ea4a46
      az aks get-credentials --resource-group rg-nordcloud-ghost --name ghost-k8s-cluster

- task: CmdLine@2
  displayName: Helm Install Istio
  inputs:
    script: |
      $(System.DefaultWorkingDirectory)\k8s-ghost-helm\scripts\istio.sh

- task: CmdLine@2
  displayName: Helm Install kiali
  inputs:
    script: |
      $(System.DefaultWorkingDirectory)\k8s-ghost-helm\scripts\kiali.sh

- task: CmdLine@2
  displayName: Helm Install prometheus
  inputs:
    script: |
      $(System.DefaultWorkingDirectory)\k8s-ghost-helm\scripts\prometheus.sh

- task: CmdLine@2
  displayName: Helm Install ghost
  inputs:
    script: |
      $(System.DefaultWorkingDirectory)\k8s-ghost-helm\scripts\ghost.sh