# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: 
  name: Kaushik_Laptop # Name of a pool. 
  vmImage: DESKTOP-A9DASJR

steps:    
- task: CmdLine@2
  displayName: az login
  inputs:
    script: |
      "%ProgramFiles%\Git\bin\bash.exe" $(System.DefaultWorkingDirectory)\k8s-ghost-helm\az.kubectl.sh

- task: CmdLine@2
  displayName: Helm Install 
  inputs:
    script: |
      "%ProgramFiles%\Git\bin\bash.exe" $(System.DefaultWorkingDirectory)\k8s-ghost-helm\install.sh