# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: 
  name: Kaushik_Laptop # Name of a pool. 
  vmImage: DESKTOP-A9DASJR

steps:    

- task: CmdLine@2
  displayName: az login
  inputs:
    script: |
      $(System.DefaultWorkingDirectory)\k8s-ghost-helm\scripts\az.kubectl.sh

- task: CmdLine@2
  displayName: Helm Install Istio
  inputs:
    script: |
      $(System.DefaultWorkingDirectory)\k8s-ghost-helm\scripts\istio.sh

- task: CmdLine@2
  displayName: Helm Install kiali
  inputs:
    script: |
      $(System.DefaultWorkingDirectory)\k8s-ghost-helm\scripts\kiali.sh

- task: CmdLine@2
  displayName: Helm Install prometheus
  inputs:
    script: |
      $(System.DefaultWorkingDirectory)\k8s-ghost-helm\scripts\prometheus.sh

- task: CmdLine@2
  displayName: Helm Install ghost
  inputs:
    script: |
      $(System.DefaultWorkingDirectory)\k8s-ghost-helm\scripts\ghost.sh